import { makeKey } from '../../core/utilities.js'

/**
 * @typedef {Object} GridMap
 * @property {function(number, number): boolean} inBounds - Checks if row and column are within grid bounds
 */

/**
 * Manages operations on cells surrounding a given coordinate.
 * Provides utilities to iterate, map, and collect neighboring cells
 * within a grid while respecting boundary constraints.
 *
 * @class SurroundingCellsHelper
 */
export class SurroundingCellsHelper {
  /**
   * Neighborhood span constants for 8-connected adjacency (3x3 kernel).
   * Covers all cells within one step in any direction (including diagonals).
   *
   * @readonly
   */
  static #NEIGHBORHOOD = {
    MIN_DELTA: -1,
    MAX_DELTA: 1
  }

  /**
   * Iterates over all in-bounds cells in the 3×3 neighborhood around (r, c).
   * Includes the center cell itself. Stops iteration if callback returns false.
   *
   * @param {GridMap} map - Grid map with inBounds(row, col) method
   * @param {number} r - Center row coordinate
   * @param {number} c - Center column coordinate
   * @param {function(number, number): void} callback - Function(row, col) called for each cell in neighborhood
   * @returns {void}
   *
   * @example
   * SurroundingCellsHelper.forEachSurroundingCell(map, 5, 5, (r, c) => {
   *   console.log(`Cell at (${r}, ${c})`);
   * });
   */
  static forEachSurroundingCell (map, r, c, callback) {
    const { MIN_DELTA, MAX_DELTA } = this.#NEIGHBORHOOD

    for (let dr = MIN_DELTA; dr <= MAX_DELTA; dr++) {
      for (let dc = MIN_DELTA; dc <= MAX_DELTA; dc++) {
        const row = r + dr
        const col = c + dc
        if (map.inBounds(row, col)) {
          callback(row, col)
        }
      }
    }
  }

  /**
   * Generic reducer for surrounding cells. Collects neighbor coordinates
   * into a target collection using a provided reducer function.
   *
   * @private
   * @param {GridMap} map - Grid map with inBounds(row, col) method
   * @param {number} r - Center row coordinate
   * @param {number} c - Center column coordinate
   * @param {*} initialCollection - Starting collection (Set, Object, Array, etc.)
   * @param {function(*, number, number): void} reducer - Function(collection, row, col) that mutates collection
   * @returns {*} The populated collection
   */
  static #collectSurroundingCells (map, r, c, initialCollection, reducer) {
    this.forEachSurroundingCell(map, r, c, (row, col) => {
      reducer(initialCollection, row, col)
    })
    return initialCollection
  }

  /**
   * Returns a Set of key strings for all surrounding cells.
   * Keys are generated via makeKey(row, col).
   *
   * @param {GridMap} map - Grid map with inBounds(row, col) method
   * @param {number} r - Center row coordinate
   * @param {number} c - Center column coordinate
   * @returns {Set<string>} Set of cell keys
   *
   * @example
   * const neighbors = SurroundingCellsHelper.asKeySet(map, 5, 5);
   * if (neighbors.has(makeKey(4, 5))) { // cell above
   *   // do something
   * }
   */
  static asKeySet (map, r, c) {
    return this.#collectSurroundingCells(
      map,
      r,
      c,
      new Set(),
      (set, row, col) => set.add(makeKey(row, col))
    )
  }

  /**
   * Returns an object map keyed by cell key strings, with values
   * generated by a custom maker function.
   *
   * @param {GridMap} map - Grid map with inBounds(row, col) method
   * @param {number} r - Center row coordinate
   * @param {number} c - Center column coordinate
   * @param {function(number, number): *} maker - Function(row, col) → value for that cell
   * @returns {Object<string, *>} Map of cell keys to maker results
   *
   * @example
   * const coordMap = SurroundingCellsHelper.asObjectMap(
   *   map, 5, 5,
   *   (r, c) => ({ row: r, col: c })
   * );
   */
  static asObjectMap (map, r, c, maker) {
    return this.#collectSurroundingCells(map, r, c, {}, (obj, row, col) => {
      obj[makeKey(row, col)] = maker(row, col)
    })
  }

  /**
   * Returns an array of values generated by a maker function
   * for all surrounding cells.
   *
   * @param {GridMap} map - Grid map with inBounds(row, col) method
   * @param {number} r - Center row coordinate
   * @param {number} c - Center column coordinate
   * @param {function(number, number): *} maker - Function(row, col) → value for that cell
   * @returns {Array<*>} Array of maker results
   *
   * @example
   * const neighbors = SurroundingCellsHelper.asArray(
   *   map, 5, 5,
   *   (r, c) => map.cellAt(r, c)
   * );
   */
  static asArray (map, r, c, maker) {
    return this.#collectSurroundingCells(map, r, c, [], (arr, row, col) => {
      arr.push(maker(row, col))
    })
  }
}
